### ISSUE TITLE
Vue routing(history mode)と実際のURLの対応付け

### ISSUE THREAD

**Issue by hassaku63** [hassaku63/bibuli-front#44]
例えば、 https://my-app.cloudfront.net/search でブラウザリフレッシュをかけると、存在しない `/search` をリクエストしてしまい403が返ってしまう。

CloudFrontによるハンドリングか、もしくはVue側でリダイレクトするなどの対処がいる

**Comment by hassaku63** [comment]
alphaを出す上でこのバグを修正するかどうか。判断はチーム内で要相談

**Comment by hassaku63** [comment]
参考 https://area-b.com/blog/2017/12/02/2205/

**Comment by kkato1030** [comment]
対応ずみと判断。クローズします。
